"""empty message

Revision ID: 287bd675a0e7
Revises: 717927db0c7
Create Date: 2015-03-18 18:49:33.314192

"""

# revision identifiers, used by Alembic.
revision = '287bd675a0e7'
down_revision = '717927db0c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=40), nullable=True))
    op.create_index('ix_users_access', 'users', ['access'], unique=False)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_access', table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'access')
    ### end Alembic commands ###
